"""CPU checks for the boot-fast loader levers (files/ours/*).

  T1  The patched safetensors iterator (window on, window off, trace on)
      yields the same (name, bytes) sequence as the image iterator. With the
      PLE-only skip, it yields the image sequence without the names of the
      skipped files, in the same order.
  T2  The file glob matches every needed file (a superset, never less), for
      the real index and for random file sets.
  T4  The expert-mapping index gives the same entries in the same order as
      the stock `weight_name in qual_name` scan, for every expert name of the
      index and for edge names.
  T6  The offload, drafter and PLE-only file sets from the real index.

T2 and T6 run on the host. T1 and T4 need torch, safetensors and vLLM, so
they run in the image (no GPU):

    docker run --rm --cpus 4 --memory 8g --entrypoint python3 \\
        -v $PWD:/r:ro -v <snapshot>:/snap:ro -e BF_SNAPSHOT=/snap \\
        vllm/vllm-openai:qwen38-flash-next -m unittest /r/tests/test_boot_fast.py

Environment: BF_SNAPSHOT (a snapshot dir with model.safetensors.index.json),
BF_MTP_SOURCE (files/mtp_patched.py, generated by start.sh), BF_T1_REAL
(space-separated real shard paths for T1; L0 only, it reads the files).
"""
import ast
import fnmatch
import hashlib
import importlib.util
import json
import os
import random
import re
import sys
import tempfile
import time
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OURS = REPO / "files" / "ours"
SNAP = os.environ.get(
    "BF_SNAPSHOT",
    "/models/usman/hf/hub/models--Mia-AiLab--Qwen3.8-Flash-Next-NVFP4/snapshots/"
    "925d7be6c14c6c9442ef83e8f05b5a3c39304f69")
MTP_SOURCE = os.environ.get("BF_MTP_SOURCE", str(REPO / "files" / "mtp_patched.py"))


def load_file_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_functions(path, names):
    """Compile only the named top-level functions of a source file."""
    tree = ast.parse(Path(path).read_text())
    body = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in names]
    ns = {}
    exec(compile(ast.Module(body=body, type_ignores=[]), str(path), "exec"), ns)
    return ns


globs = load_file_module("boot_fast_globs", OURS / "boot_fast_globs.py")
HAVE_INDEX = os.path.isfile(os.path.join(SNAP, "model.safetensors.index.json"))
try:
    import torch  # noqa: F401
    import vllm  # noqa: F401
    HAVE_VLLM = True
except Exception:  # noqa: BLE001
    HAVE_VLLM = False


# --------------------------------------------------------------------- T2, T6
class GlobTests(unittest.TestCase):
    def test_superset_random_sets(self):
        rng = random.Random(1234)
        universe = [f"model-{i:05d}-of-00034.safetensors" for i in range(1, 35)]
        for _ in range(2000):
            need = sorted(rng.sample(universe, rng.randint(1, 8)))
            g = globs.make_glob(need)
            self.assertIsNotNone(g)
            matched = {f for f in universe if fnmatch.fnmatchcase(f, g)}
            self.assertTrue(set(need) <= matched, (need, g))
            globs.check_glob(g, need, universe)

    def test_random_names(self):
        rng = random.Random(99)
        alphabet = "abc-_.019"
        for _ in range(500):
            width = rng.randint(1, 12)
            need = sorted({"".join(rng.choice(alphabet) for _ in range(width))
                           for _ in range(rng.randint(1, 6))})
            g = globs.make_glob(need)
            for f in need:
                self.assertTrue(fnmatch.fnmatchcase(f, g), (need, g))

    def test_no_glob(self):
        self.assertIsNone(globs.make_glob([]))
        self.assertIsNone(globs.make_glob(["a.safetensors", "ab.safetensors"]))
        self.assertIsNone(globs.make_glob(["a[1].safetensors"]))

    @unittest.skipUnless(HAVE_INDEX and os.path.isfile(MTP_SOURCE), "no index or mtp source")
    def test_real_index(self):
        wm = globs.load_weight_map(SNAP)
        universe = sorted(set(wm.values()))
        remap = globs.load_remap(MTP_SOURCE)
        mtp = globs.mtp_files(wm, remap)
        self.assertEqual(mtp, ["model-00033-of-00034.safetensors",
                               "model-00034-of-00034.safetensors"])
        g = globs.make_glob(mtp)
        self.assertEqual(g, "model-0003[34]-of-00034.safetensors")
        self.assertEqual(globs.check_glob(g, mtp, universe), [])
        # Every drafter name is in a matched file.
        for name, f in wm.items():
            if remap(name) is not None:
                self.assertTrue(fnmatch.fnmatchcase(f, g), name)
        # T6: offload worker files.
        ple = globs.ple_offload_files(wm)
        self.assertEqual(ple, ["model-00001-of-00034.safetensors",
                               "model-00019-of-00034.safetensors"])
        gp = globs.make_glob(ple)
        self.assertEqual(gp, "model-000[01][19]-of-00034.safetensors")
        for name, f in wm.items():
            if ".ple." in name and not globs.PACKED_PLE.search(name):
                self.assertTrue(fnmatch.fnmatchcase(f, gp), name)
        skip = globs.ple_only_files(wm)
        self.assertEqual(skip, [f"model-{i:05d}-of-00034.safetensors" for i in range(2, 19)])
        # The glob never matches the files that the loader must not read twice.
        on_disk = os.listdir(SNAP)
        globs.check_glob(g, mtp, on_disk)
        globs.check_glob(gp, ple, on_disk)


# ------------------------------------------------------------------------- T1
def _seq(it):
    import torch
    out = []
    for name, t in it:
        b = t.contiguous().reshape(-1).view(torch.uint8).numpy().tobytes() if t.numel() else b""
        out.append((name, str(t.dtype), tuple(t.shape), hashlib.blake2b(b, digest_size=16).hexdigest()))
    return out


@unittest.skipUnless(HAVE_VLLM, "needs the image (torch, safetensors, vllm)")
class IteratorTests(unittest.TestCase):
    ENV = ("VLLM_ST_WINDOW", "VLLM_ST_WINDOW_METHOD", "VLLM_ST_WINDOW_THREADS",
           "VLLM_ST_WINDOW_MODE", "VLLM_ST_BUFFER_PINNED",
           "VLLM_ST_WINDOW_FLOOR_GIB", "VLLM_ST_DROP_DONE", "VLLM_ST_SKIP_PLE_ONLY",
           "VLLM_ST_TRACE_DIR", "VLLM_PLE_CPU_OFFLOAD", "VLLM_PLE_PACKED_TABLE_DIR",
           "VLLM_MTP_FILE_GLOB")

    @classmethod
    def setUpClass(cls):
        import torch
        from safetensors.torch import save_file
        import vllm.model_executor.model_loader.weight_utils as orig
        cls.orig = orig
        cls.patched = load_file_module("bf_weight_utils", OURS / "weight_utils.py")
        cls.tmp = tempfile.TemporaryDirectory()
        g = torch.Generator().manual_seed(7)
        cls.files, cls.ple_only = [], []
        for i in range(1, 8):
            tensors = {}
            if i in (2, 3):
                for s in range(4):
                    p = "model.language_model.layers.1.ple.ple_embedding.ngram_embedding"
                    tensors[f"{p}.shard_{s}.weight"] = torch.randint(0, 255, (64, 16), dtype=torch.uint8, generator=g)
                    tensors[f"{p}.shard_{s}.weight_scale"] = torch.rand(64, 1, generator=g).to(torch.float8_e4m3fn)
            else:
                for e in (0, 1, 11, 111, 511):
                    base = f"model.language_model.layers.{i}.mlp.experts.{e}"
                    tensors[f"{base}.down_proj.weight"] = torch.randint(0, 255, (32, 24), dtype=torch.uint8, generator=g)
                    tensors[f"{base}.down_proj.weight_scale"] = torch.rand(32, 3, generator=g).to(torch.float8_e4m3fn)
                    tensors[f"{base}.down_proj.weight_scale_2"] = torch.rand((), generator=g)
                    tensors[f"{base}.gate_proj.weight"] = torch.randint(0, 255, (48, 24), dtype=torch.uint8, generator=g)
                tensors[f"model.language_model.layers.{i}.input_layernorm.weight"] = torch.rand(40, generator=g).to(torch.bfloat16)
                tensors[f"model.language_model.layers.{i}.big"] = torch.rand(300_000, generator=g)
                if i == 1:
                    tensors["model.language_model.layers.1.ple.ple_embedding.layer_multipliers"] = torch.rand(3, generator=g)
            path = os.path.join(cls.tmp.name, f"model-{i:05d}-of-00007.safetensors")
            save_file(tensors, path)
            cls.files.append(path)
            if i in (2, 3):
                cls.ple_only.append(path)

    @classmethod
    def tearDownClass(cls):
        cls.tmp.cleanup()

    def setUp(self):
        self.saved = {k: os.environ.pop(k, None) for k in self.ENV}

    def tearDown(self):
        for k, v in self.saved.items():
            os.environ.pop(k, None)
            if v is not None:
                os.environ[k] = v

    def stock(self, files):
        return _seq(self.orig.safetensors_weights_iterator(files, False, "lazy"))

    def patched_seq(self, files, **env):
        os.environ.update({k: str(v) for k, v in env.items()})
        try:
            return _seq(self.patched.safetensors_weights_iterator(files, False, "lazy"))
        finally:
            for k in env:
                os.environ.pop(k, None)

    def test_knobs_off(self):
        self.assertEqual(self.patched_seq(self.files), self.stock(self.files))

    def test_window(self):
        want = self.stock(self.files)
        for n in (1, 2, 9):
            for method in ("read", "willneed"):
                for threads in (1, 3):
                    got = self.patched_seq(self.files, VLLM_ST_WINDOW=n, VLLM_ST_WINDOW_METHOD=method,
                                           VLLM_ST_WINDOW_THREADS=threads, VLLM_ST_DROP_DONE=1,
                                           VLLM_ST_WINDOW_FLOOR_GIB=0)
                    self.assertEqual(got, want, (n, method, threads))

    def test_buffer_mode(self):
        want = self.stock(self.files)
        for threads in (1, 4):
            got = self.patched_seq(self.files, VLLM_ST_WINDOW=1, VLLM_ST_WINDOW_MODE="buffer",
                                   VLLM_ST_WINDOW_THREADS=threads, VLLM_ST_WINDOW_FLOOR_GIB=0)
            self.assertEqual(got, want, threads)
        got = self.patched_seq(self.files, VLLM_ST_WINDOW=1, VLLM_ST_WINDOW_MODE="buffer",
                               VLLM_ST_SKIP_PLE_ONLY=1, VLLM_PLE_CPU_OFFLOAD=1,
                               VLLM_PLE_PACKED_TABLE_DIR="/x", VLLM_ST_WINDOW_FLOOR_GIB=0)
        drop = set()
        for f in self.ple_only:
            drop |= {n for n, *_ in self.stock([f])}
        self.assertEqual(got, [x for x in want if x[0] not in drop])

    def test_skip_ple_only(self):
        want = [x for x in self.stock(self.files)]
        drop = set()
        for f in self.ple_only:
            drop |= {n for n, *_ in self.stock([f])}
        want = [x for x in want if x[0] not in drop]
        got = self.patched_seq(self.files, VLLM_ST_WINDOW=1, VLLM_ST_SKIP_PLE_ONLY=1,
                               VLLM_PLE_CPU_OFFLOAD=1, VLLM_PLE_PACKED_TABLE_DIR="/x",
                               VLLM_ST_WINDOW_FLOOR_GIB=0)
        self.assertEqual(got, want)
        self.assertTrue(drop)
        # Without the offload knobs, the skip does not engage.
        got = self.patched_seq(self.files, VLLM_ST_WINDOW=1, VLLM_ST_SKIP_PLE_ONLY=1,
                               VLLM_ST_WINDOW_FLOOR_GIB=0)
        self.assertEqual(got, self.stock(self.files))

    def test_trace(self):
        with tempfile.TemporaryDirectory() as d:
            got = self.patched_seq(self.files, VLLM_ST_TRACE_DIR=d)
            self.assertEqual(got, self.stock(self.files))
            traces = sorted(Path(d).glob("trace-gpu-*.tsv"))
            self.assertEqual(len(traces), 1)
            rows = [ln.split("\t") for ln in traces[0].read_text().splitlines()]
            self.assertEqual([r[1] for r in rows], [x[0] for x in got])
            self.assertTrue(all(r[4].isdigit() and r[5].isdigit() for r in rows))

    @unittest.skipUnless(os.environ.get("BF_T1_REAL"), "BF_T1_REAL not set (L0 only)")
    def test_real_shards(self):
        files = os.environ["BF_T1_REAL"].split()
        t0 = time.time()
        want = self.stock(files)
        t1 = time.time()
        got = self.patched_seq(files, VLLM_ST_WINDOW=1, VLLM_ST_DROP_DONE=0,
                               VLLM_ST_WINDOW_FLOOR_GIB=0)
        t2 = time.time()
        self.assertEqual(got, want)
        got_b = self.patched_seq(files, VLLM_ST_WINDOW=1, VLLM_ST_WINDOW_MODE="buffer",
                                 VLLM_ST_WINDOW_THREADS=4, VLLM_ST_WINDOW_FLOOR_GIB=0)
        t3 = time.time()
        self.assertEqual(got_b, want)
        print(f"\nT1 real: {len(want)} tensors, stock {t1 - t0:.1f}s, window {t2 - t1:.1f}s, "
              f"buffer {t3 - t2:.1f}s", file=sys.stderr)


# ------------------------------------------------------------------------- T4
@unittest.skipUnless(HAVE_VLLM, "needs the image (vllm)")
class ExpertLookupTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from vllm.model_executor.layers.fused_moe.routed_experts import RoutedExperts
        cls.RE = RoutedExperts
        ns = load_functions(OURS / "routed_experts.py", {"_bf_expert_index", "_bf_expert_hits"})
        cls.index = staticmethod(ns["_bf_expert_index"])
        cls.hits = staticmethod(ns["_bf_expert_hits"])

    def mapping(self, n, gate="gate_proj", up="up_proj", down="down_proj", lora=""):
        return self.RE.build_expert_params_mapping(
            gate, down, up, num_experts=n, routed_experts_prefix="",
            lora_base_layer_prefix=lora, include_fused=True)

    def stock(self, mapping, q):
        return [m for m in mapping if m[1] in q]

    def check(self, mapping, names):
        idx = self.index(mapping)
        self.assertIsNotNone(idx)
        for q in names:
            self.assertEqual(self.hits(idx, mapping, q), self.stock(mapping, q), q)

    def edge_names(self, layer="language_model.model.layers.7.mlp.experts"):
        out = []
        for e in (0, 1, 11, 111, 511, 512, 5, 51):
            for p in ("gate_proj", "up_proj", "down_proj", "gate_up_proj"):
                for s in ("weight", "weight_scale", "weight_scale_2", "input_scale", "bias"):
                    out.append(f"{layer}.{e}.{p}.{s}")
        out += [f"{layer}.gate_up_proj.weight", f"{layer}.down_proj.weight",
                f"{layer}.gate_up_proj_bias", f"{layer}.down_proj_bias",
                f"{layer}.experts.3.down_proj.weight", "x.experts.1.experts.11.gate_proj.weight",
                f"{layer}.1.gate_proj.base_layer.weight", "experts.", ""]
        return out

    def test_edges(self):
        for n in (512, 513, 8):
            self.check(self.mapping(n), self.edge_names())
        self.check(self.mapping(16, "w1", "w3", "w2"),
                   [n.replace("gate_proj", "w1").replace("up_proj", "w3").replace("down_proj", "w2")
                    for n in self.edge_names()])
        self.check(self.mapping(16, lora="base_layer."), self.edge_names())

    def test_env_off(self):
        os.environ["VLLM_EXPERT_LOOKUP"] = "0"
        try:
            self.assertIsNone(self.index(self.mapping(8)))
        finally:
            del os.environ["VLLM_EXPERT_LOOKUP"]

    @unittest.skipUnless(HAVE_INDEX, "no index")
    def test_real_index(self):
        wm = globs.load_weight_map(SNAP)
        mapping = self.mapping(512)
        self.assertEqual(len(mapping), 2563)
        pat = re.compile(r"^model\.language_model\.layers\.(\d+)\.mlp\.(experts\..*)$")
        names = []
        for n in wm:
            m = pat.match(n)
            if m:
                names.append(f"language_model.model.layers.{m.group(1)}.mlp.{m.group(2)}")
        mtp = re.compile(r"^mtp\.layers\.(\d+)\.mlp\.(experts\..*)$")
        names += [f"model.layers.{m.group(1)}.mlp.{m.group(2)}" for n in wm if (m := mtp.match(n))]
        self.assertGreater(len(names), 290_000)
        idx = self.index(mapping)
        t0 = time.time()
        new = [self.hits(idx, mapping, q) for q in names]
        t1 = time.time()
        old = [self.stock(mapping, q) for q in names[:20000]]
        t2 = time.time()
        self.assertEqual(new[:20000], old)
        # The full stock scan is slow; check all names in parts of 20k.
        for s in range(20000, len(names), 20000):
            part = names[s : s + 20000]
            self.assertEqual(new[s : s + 20000], [self.stock(mapping, q) for q in part])
        self.assertTrue(all(new), "a real expert name matched no entry")
        per_new = (t1 - t0) / len(names) * 1e6
        per_old = (t2 - t1) / 20000 * 1e6
        print(f"\nT4 real: {len(names)} names; match cost {per_old:.1f} us (stock scan) vs "
              f"{per_new:.2f} us (index) per tensor; stock total ~{per_old * len(names) / 1e6:.0f}s",
              file=sys.stderr)


# ------------------------------------------------------------ patch structure
def _top(path):
    return {getattr(n, "name", None): n for n in ast.parse(Path(path).read_text()).body
            if isinstance(n, (ast.FunctionDef, ast.ClassDef, ast.AsyncFunctionDef))}


class PatchStructureTests(unittest.TestCase):
    """Each generated file changes only the functions that its patch names.

    Every other top-level function and class, and every other method of a
    changed class, has the same AST (decorators too) as the image file. The
    new _bf_ helpers have no decorator.
    """
    CHANGED = {
        "weight_utils.py": {"safetensors_weights_iterator": None},
        "routed_experts.py": {"RoutedExperts": {"load_weights"}},
        "model_runner.py": {"GPUModelRunner": {"load_model"}},
        "base.py": {"BaseRenderer": {"warmup"}},
    }

    def compare(self, fname):
        new_p, old_p = OURS / fname, OURS / (fname + ".orig")
        if not (new_p.is_file() and old_p.is_file()):
            self.skipTest(f"{fname} not generated (start.sh makes it)")
        new, old = _top(new_p), _top(old_p)
        changed = self.CHANGED[fname]
        for name, node in old.items():
            self.assertIn(name, new, name)
            if name not in changed:
                self.assertEqual(ast.dump(node), ast.dump(new[name]), f"{fname}: {name} changed")
                continue
            self.assertEqual([ast.dump(d) for d in node.decorator_list],
                             [ast.dump(d) for d in new[name].decorator_list], name)
            methods = changed[name]
            if methods is None:
                continue
            om = {m.name: m for m in node.body if isinstance(m, ast.FunctionDef)}
            nm = {m.name: m for m in new[name].body if isinstance(m, ast.FunctionDef)}
            self.assertEqual(set(om), set(nm), name)
            for m in om:
                if m not in methods:
                    self.assertEqual(ast.dump(om[m]), ast.dump(nm[m]), f"{fname}: {name}.{m} changed")
        for name, node in new.items():
            if name not in old:
                self.assertTrue(name.startswith(("_bf_", "_BootFast")), f"{fname}: new {name}")
                self.assertEqual(node.decorator_list, [], f"{fname}: {name} is decorated")

    def test_weight_utils(self):
        self.compare("weight_utils.py")

    def test_routed_experts(self):
        self.compare("routed_experts.py")

    def test_model_runner(self):
        self.compare("model_runner.py")

    def test_base(self):
        self.compare("base.py")


if __name__ == "__main__":
    unittest.main()
