"""CPU checks for the boot-fast loader levers (files/ours/*).

  T1  The patched safetensors iterator (window on, window off, trace on)
      yields the same (name, bytes) sequence as the image iterator. With the
      PLE-only skip, it yields the image sequence without the names of the
      skipped files, in the same order.
  T2  The file glob matches every needed file (a superset, never less), for
      the real index and for random file sets.
  T4  The expert-mapping index gives the same entries in the same order as
      the stock `weight_name in qual_name` scan, for every expert name of the
      index and for edge names.
  T6  The offload, drafter and PLE-only file sets from the real index.

T2 and T6 run on the host. T1 and T4 need torch, safetensors and vLLM, so
they run in the image (no GPU):

    docker run --rm --cpus 4 --memory 8g --entrypoint python3 \\
        -v $PWD:/r:ro -v <snapshot>:/snap:ro -e BF_SNAPSHOT=/snap \\
        vllm/vllm-openai:qwen38-flash-next -m unittest /r/tests/test_boot_fast.py

Environment: BF_SNAPSHOT (a snapshot dir with model.safetensors.index.json),
BF_MTP_SOURCE (files/mtp_patched.py, generated by start.sh), BF_T1_REAL
(space-separated real shard paths for T1; L0 only, it reads the files).
"""
import ast
import fnmatch
import hashlib
import importlib.util
import json
import os
import random
import re
import sys
import tempfile
import time
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OURS = REPO / "files" / "ours"
SNAP = os.environ.get(
    "BF_SNAPSHOT",
    "/models/usman/hf/hub/models--Mia-AiLab--Qwen3.8-Flash-Next-NVFP4/snapshots/"
    "925d7be6c14c6c9442ef83e8f05b5a3c39304f69")
MTP_SOURCE = os.environ.get("BF_MTP_SOURCE", str(REPO / "files" / "mtp_patched.py"))


def load_file_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_functions(path, names):
    """Compile only the named top-level functions of a source file."""
    tree = ast.parse(Path(path).read_text())
    body = [n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name in names]
    ns = {}
    exec(compile(ast.Module(body=body, type_ignores=[]), str(path), "exec"), ns)
    return ns


globs = load_file_module("boot_fast_globs", OURS / "boot_fast_globs.py")
HAVE_INDEX = os.path.isfile(os.path.join(SNAP, "model.safetensors.index.json"))
try:
    import torch  # noqa: F401
    import vllm  # noqa: F401
    HAVE_VLLM = True
except Exception:  # noqa: BLE001
    HAVE_VLLM = False


# --------------------------------------------------------------------- T2, T6
class GlobTests(unittest.TestCase):
    def test_superset_random_sets(self):
        rng = random.Random(1234)
        universe = [f"model-{i:05d}-of-00034.safetensors" for i in range(1, 35)]
        for _ in range(2000):
            need = sorted(rng.sample(universe, rng.randint(1, 8)))
            g = globs.make_glob(need)
            self.assertIsNotNone(g)
            matched = {f for f in universe if fnmatch.fnmatchcase(f, g)}
            self.assertTrue(set(need) <= matched, (need, g))
            globs.check_glob(g, need, universe)

    def test_random_names(self):
        rng = random.Random(99)
        alphabet = "abc-_.019"
        for _ in range(500):
            width = rng.randint(1, 12)
            need = sorted({"".join(rng.choice(alphabet) for _ in range(width))
                           for _ in range(rng.randint(1, 6))})
            g = globs.make_glob(need)
            for f in need:
                self.assertTrue(fnmatch.fnmatchcase(f, g), (need, g))

    def test_no_glob(self):
        self.assertIsNone(globs.make_glob([]))
        self.assertIsNone(globs.make_glob(["a.safetensors", "ab.safetensors"]))
        self.assertIsNone(globs.make_glob(["a[1].safetensors"]))

    @unittest.skipUnless(HAVE_INDEX and os.path.isfile(MTP_SOURCE), "no index or mtp source")
    def test_real_index(self):
        wm = globs.load_weight_map(SNAP)
        universe = sorted(set(wm.values()))
        remap = globs.load_remap(MTP_SOURCE)
        mtp = globs.mtp_files(wm, remap)
        self.assertEqual(mtp, ["model-00033-of-00034.safetensors",
                               "model-00034-of-00034.safetensors"])
        g = globs.make_glob(mtp)
        self.assertEqual(g, "model-0003[34]-of-00034.safetensors")
        self.assertEqual(globs.check_glob(g, mtp, universe), [])
        # Every drafter name is in a matched file.
        for name, f in wm.items():
            if remap(name) is not None:
                self.assertTrue(fnmatch.fnmatchcase(f, g), name)
        # T6: offload worker files.
        ple = globs.ple_offload_files(wm)
        self.assertEqual(ple, ["model-00001-of-00034.safetensors",
                               "model-00019-of-00034.safetensors"])
        gp = globs.make_glob(ple)
        self.assertEqual(gp, "model-000[01][19]-of-00034.safetensors")
        for name, f in wm.items():
            if ".ple." in name and not globs.PACKED_PLE.search(name):
                self.assertTrue(fnmatch.fnmatchcase(f, gp), name)
        skip = globs.ple_only_files(wm)
        self.assertEqual(skip, [f"model-{i:05d}-of-00034.safetensors" for i in range(2, 19)])
        # The glob never matches the files that the loader must not read twice.
        on_disk = os.listdir(SNAP)
        globs.check_glob(g, mtp, on_disk)
        globs.check_glob(gp, ple, on_disk)



if __name__ == "__main__":
    unittest.main()
