#!/usr/bin/env python3
"""Generate files/ours/routed_experts.py: find the expert mapping entries of a
checkpoint tensor through an exact substring index (boot-fast R4).

Why: RoutedExperts.load_weights tests each checkpoint tensor against every
entry of the expert mapping (2,563 entries for 512 experts) with
`weight_name not in qual_name`. For a non-fused (2-D) tensor the loop never
breaks. The target has 294,912 expert tensors, so the scan costs about
750 M substring tests (tens of seconds of CPU in the load pass).

The new path gives the loop body the same entries in the same order:
  * Once for each load_weights call, it builds a dict weight_name -> entry
    indices, the set of weight_name lengths, and P, the longest common prefix
    of all weight_names.
  * Each weight_name starts with P. So a weight_name that occurs in qual_name
    starts at an occurrence of P. For each occurrence of P, and for each
    length, it looks up the slice. The hits are the entries whose
    weight_name occurs in qual_name: the stock set.
  * It removes duplicate indices and sorts the hits by entry index: the stock
    order.
The loop body does not change, and the stock `weight_name not in qual_name`
test stays in the body. A fused (3-D) tensor, where the stock loop has an early
break, and a mapping with an empty P use the stock loop. VLLM_EXPERT_LOOKUP=0
also gives the stock loop.

    patch_routed_experts_lookup.py      (reads files/ours/routed_experts.py.orig)
"""
import hashlib
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ORIG = os.path.join(HERE, "routed_experts.py.orig")
OUT = os.path.join(HERE, "routed_experts.py")
# vllm/vllm-openai:qwen38-flash-next, RepoDigest sha256:fc120ece0a38...
ORIG_MD5 = "8097d2173542bd3174286f6f2688daa9"

ANCHOR_MAP = '''        expert_mapping = self.get_expert_mapping(include_fused=True)
        for expert_name, loaded_weight in weights:
            qual_name = f"{self.layer_name}.{expert_name}"
            # Fused expert weights can be identified by their 3D tensors
            is_fused = loaded_weight.dim() == 3
            matched = False
            for param_name, weight_name, expert_id, shard_id in expert_mapping:
                if weight_name not in qual_name:
'''
NEW_MAP = '''        expert_mapping = self.get_expert_mapping(include_fused=True)
        _bf_index = _bf_expert_index(expert_mapping)
        for expert_name, loaded_weight in weights:
            qual_name = f"{self.layer_name}.{expert_name}"
            # Fused expert weights can be identified by their 3D tensors
            is_fused = loaded_weight.dim() == 3
            matched = False
            for param_name, weight_name, expert_id, shard_id in (
                expert_mapping
                if is_fused or _bf_index is None
                else _bf_expert_hits(_bf_index, expert_mapping, qual_name)
            ):
                if weight_name not in qual_name:
'''

ANCHOR_CLASS = "\n@PluggableLayer.register(\"routed_experts\")\nclass RoutedExperts("

HELPERS = r'''

# --- boot-fast R4: exact substring index for the expert mapping ------------
# Generated by files/ours/patch_routed_experts_lookup.py. See that file.
def _bf_expert_index(mapping):
    """Return (by_name, lengths, prefix) for the mapping, or None (stock loop)."""
    import os as _os

    if _os.environ.get("VLLM_EXPERT_LOOKUP", "1") == "0" or not mapping:
        return None
    names = [entry[1] for entry in mapping]
    prefix = _os.path.commonprefix(names)
    if not prefix:
        return None
    by_name = {}
    for i, name in enumerate(names):
        by_name.setdefault(name, []).append(i)
    lengths = sorted({len(name) for name in by_name})
    return by_name, lengths, prefix


def _bf_expert_hits(index, mapping, qual_name):
    """The mapping entries whose weight_name occurs in qual_name, in mapping order."""
    by_name, lengths, prefix = index
    hits = set()
    pos = qual_name.find(prefix)
    while pos >= 0:
        for n in lengths:
            idx = by_name.get(qual_name[pos : pos + n])
            if idx is not None:
                hits.update(idx)
        pos = qual_name.find(prefix, pos + 1)
    return [mapping[i] for i in sorted(hits)]


# --- end boot-fast ----------------------------------------------------------
'''


def main():
    with open(ORIG, "rb") as fh:
        raw = fh.read()
    md5 = hashlib.md5(raw).hexdigest()
    if md5 != ORIG_MD5:
        sys.exit(f"routed_experts.py.orig md5 {md5} != {ORIG_MD5}: image changed, re-check the patch")
    s = raw.decode()
    for name, anchor in (("map", ANCHOR_MAP), ("class", ANCHOR_CLASS)):
        if s.count(anchor) != 1:
            sys.exit(f"anchor '{name}' found {s.count(anchor)} times (want 1)")
    s = s.replace(ANCHOR_MAP, NEW_MAP, 1)
    s = s.replace(ANCHOR_CLASS, HELPERS + ANCHOR_CLASS, 1)
    with open(OUT, "w") as fh:
        fh.write(s)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
